//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement_DataAccess_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int Id { get; set; }
        public long Student_Number { get; set; }
        public int Book_Number { get; set; }
        public System.DateTime Issued_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
    }
}
