//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement_DataAccess_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public long Student_Number { get; set; }
        public string Name { get; set; }
        public string E_mail_ID { get; set; }
        public string Address { get; set; }
        public long Contact_Number { get; set; }
        public string Gender { get; set; }
        public int LibraryNumber { get; set; }
    }
}
